# Generated by Django 5.2.3 on 2025-10-06 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('encarregado', 'Encarregado'), ('vaqueiro', 'Vaqueiro')], max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='colaboradores/')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cultura_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('producao_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_terra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria_receita', models.CharField(blank=True, choices=[('venda_animais', 'Venda de Animais'), ('venda_leite', 'Venda de Leite'), ('arrendamento', 'Arrendamentos'), ('outras', 'Outras')], max_length=50, null=True)),
                ('categoria_despesa', models.CharField(blank=True, choices=[('encarregado', 'Encarregado'), ('vaqueiros', 'Vaqueiros'), ('assistencia', 'Assistência Técnica'), ('remuneracao', 'Remuneração'), ('adm', 'Desp. Administrativas'), ('financeiras', 'Desp. Financeiras'), ('tributarias', 'Desp. Tributárias'), ('gerais', 'Desp. Gerais')], max_length=50, null=True)),
                ('subcategoria_despesa', models.CharField(blank=True, choices=[('investimento', 'Investimento'), ('compra_animais', 'Compra de Animais')], max_length=20, null=True)),
                ('investimento', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_distribuicao', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.animal')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='propriedades/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='dashboard.propriedade')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.propriedade'),
        ),
    ]
