# Generated by Django 5.2.3 on 2025-10-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='categoria_receita',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='percentual_distribuicao',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='subcategoria_despesa',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='animal_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.colaborador'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fazenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fornecedor'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor_local_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor_local_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor_local_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor_local_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='categoria_despesa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('receita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.propriedade')),
            ],
        ),
    ]
