# Generated by Django 5.2.3 on 2025-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_lancamento_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('vaqueiro', 'Vaqueiro'), ('encarregado', 'Encarregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fotopropriedade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='propriedades/'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='cultura_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='localizacao',
            field=models.CharField(default='Não informado', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='producao_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='valor_terra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
