# Generated by Django 5.2.3 on 2025-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_fornecedor_contato_alter_colaborador_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='categoria_receita',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
