# Generated by Django 5.2.3 on 2025-10-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_lancamento_categoria_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='categoria_investimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
