# Generated by Django 5.1.1 on 2025-10-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_lancamento_categoria_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
    ]
